### ISSUE TITLE
Прохождение тестов пятнашек

### ISSUE THREAD

**Issue by aurusov** [aurusov/rdo_studio#43]
Сломались сборки под убунтой
```
Run:  ./rdo_studio -platform minimal --plugin0="1 0 2 4 5 3" -i ../models/test/plugin/game5_test/game5_test.rdox
EXIT CODE:  139
PYTHON EXIT CODE : 139
```

Как дебажить
- добавить логирования, даже в `main`
- запускать из Дженкинса сразу плюсовый код
- добавить вывод кода возврата через `echo $?`

**Comment by AlexChernov** [comment]
Решено в https://github.com/AlexChernov/rdo_studio/pull/41
